name: Deploy Site

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  deploy-docs:
    permissions:
      contents: write #  to write to gh-pages branch (peaceiris/actions-gh-pages)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
